### ISSUE TITLE
Error with "EISGIT" code pointing on "/web3-hdwallet-provider/node_modules/websocket"

### ISSUE THREAD

**Issue by shchypylov** [decentral-ee/web3-hdwallet-provider#3]
Hi, we are using your library on the project and I noticed that when I am trying to install something with npm while your library listed as dependency I get this error: 

> npm ERR! path /Users/shchypylov/Files/work/alephone/wecantokenize/node_modules/web3-hdwallet-provider/node_modules/websocket
> npm ERR! code EISGIT
> npm ERR! git /Users/shchypylov/Files/work/alephone/wecantokenize/node_modules/web3-hdwallet-provider/node_modules/websocket: Appears to be a git repo or submodule.
> npm ERR! git     /Users/shchypylov/Files/work/alephone/wecantokenize/node_modules/web3-hdwallet-provider/node_modules/websocket
> npm ERR! git Refusing to remove it. Update manually,
> npm ERR! git or move it out of the way first.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/shchypylov/.npm/_logs/2019-10-02T13_29_16_393Z-debug.log

If I am manually removing your package from package.json and install something - everything works.
May you help me with that?
Thanks!

**Comment by hellwolf** [comment]
Hi!

Quite possibility that you will need to remove the `package-lock.json` and do the `npm install` again, that usually can.

**Comment by hellwolf** [comment]
also,  truffle-hdwallet-provider has improved greatly since this package had to be introduced, consider to use the original one instead.

**Comment by shchypylov** [comment]
Thanks for your reply!
Nope, I still have this error...
Can u reproduce it on your side?

Okay, I will have a look on it!

**Comment by hellwolf** [comment]
Try these, they usually work:

* remove node_modules # of your project
* remove ~/.npm # mostly the cache

**Comment by shchypylov** [comment]
Okay, thanks!
